import { useState, useEffect } from 'react';
import Head from "next/head";
import MaterialTable from "material-table";
import { useStyles } from "../../../styles/clubs/Index.style";
import { TopBar } from "../../../src/components/navigation/TopBar";
import { MenuBar } from "../../../src/components/navigation/MenuBar";
import { tableIcons } from "../../../src/components/table/MaterialTable";
import { getAllGyms } from "../../../src/utils/fetchApi/clubs";

export default function DashboardSuperAdmin() {
  const classes = useStyles();
  const [clubs, setClubs] = useState([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    getAllGyms(setLoading, setClubs, { limit: 1000, page: 1 });
  }, []);

  return (
    <div className={classes.root}>
      <Head>
        <title>Dashboard CalFit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopBar label="Dashboard" />

      <main className={classes.main}>
        <MenuBar selected={"Clubs"} />
        <MaterialTable
          title="Clubs"
          icons={tableIcons}
          columns={[
            { title: 'Name', field: 'name' },
            {
              title: 'Admin', field: 'operationalAdminId',
            },
            { title: 'Telephone', field: 'telephone' },
          ]}
          data={clubs}
          actions={[
            {
              icon: tableIcons.Edit,
              tooltip: 'Edit Club',
              onClick: (event, rowData) => alert("You saved " + rowData.name)
            },
            rowData => ({
              icon: tableIcons.Delete,
              tooltip: 'Delete Club',
              onClick: (event, rowData) => confirm("You want to delete " + rowData.name),
              // disabled: rowData.birthYear < 2000
            })
          ]}
          options={{
            actionsColumnIndex: -1
          }}
        />

      </main>
    </div>
  );
}
