import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head';
import MaterialTable from 'material-table';
import { useStyles } from '../../../styles/classes/Index.style';
import { TopBar } from '../../../src/components/navigation/TopBar';
import { MenuBar } from '../../../src/components/navigation/MenuBar';
import { tableIcons } from '../../../src/components/table/MaterialTable';
import { getAllClasses, deleteClass } from '../../../src/utils/fetchApi/classes';

export default function ClassesSuperAdmin() {
  const styles = useStyles();
  const router = useRouter();
  const [classesList, setClassesList] = useState([]);
  const [alertClasses, setAlertClasses] = useState({
    status: false,
    message: '',
  });
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    getAllClasses(setLoading, setClassesList, { limit: 1000, page: 1 });
  }, []);

  console.log(classesList);

  useEffect(() => {
    classesList?.map((club) => {
      club.type = club.online ? 'Online' : 'Offline';
    });
  }, [classesList]);

  const handleDelete = async (id) => {
    const res = await deleteClass(setLoading, setAlertClasses, id);
    if (res.status === 202) {
      setClassesList(classesList.filter((club) => club.id !== id));
      return true;
    }
    return false;
  };

  return (
    <div className={styles.root}>
      <Head>
        <title>Classes Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <TopBar />

      <main className={styles.main}>
        <MenuBar selected={'Classes'} />
        <MaterialTable
          className={styles.table}
          title='Classes'
          icons={tableIcons}
          columns={[
            { title: 'Id', field: 'id' },
            { title: 'Name', field: 'name' },
            { title: 'Gym Id', field: 'gymID', width: '10%' },
            { title: 'Type', field: 'type', width: '10%' },
            { title: 'Category', field: 'category' },
            { title: 'Status', field: 'status' },
          ]}
          data={classesList}
          actions={[
            {
              icon: tableIcons.Edit,
              tooltip: 'Edit Class',
              onClick: (event, rowData) => router.push(`/superadmin/classes/edit/${rowData.id}`),
            },
            (rowData) => ({
              icon: tableIcons.Delete,
              tooltip: 'Delete Class',
              onClick: (event, rowData) => {
                const isDelete = confirm(`You want to delete ${rowData.name}(id: ${rowData.id}) ?`);
                if (isDelete) {
                  const success = handleDelete(rowData.id);
                  if (success) alert(`You deleted ${rowData.name}(id: ${rowData.id})`);
                  else alert(`Can't delete ${rowData.name}(id: ${rowData.id})`);
                }
              },
              // disabled: rowData.birthYear < 2000
            }),
            {
              icon: tableIcons.Add,
              tooltip: 'Add New Class',
              isFreeAction: true,
              onClick: (event) => router.push('/superadmin/classes/add'),
            },
          ]}
          options={{
            actionsColumnIndex: -1,
          }}
        />
      </main>
    </div>
  );
}
