import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head';
import MaterialTable from 'material-table';
import { Box, Container, Grid, Typography } from '@mui/material';
import { useStyles } from '../../../styles/Home.style';
import { TopBar } from '../../../src/components/navigation/TopBar';
import { MenuBar } from '../../../src/components/navigation/MenuBar';
import { getGymsCount } from '../../../src/utils/fetchApi/clubs';
import { getClassesCount } from '../../../src/utils/fetchApi/classes';

export default function ClubsSuperAdmin() {
  const [clubsCount, setClubsCount] = useState(0);
  const [classesCount, setClassesCount] = useState(1000000);
  const classes = useStyles();
  const router = useRouter();
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    getGymsCount(setLoading, setClubsCount);
    getClassesCount(setLoading, setClassesCount);
  }, []);

  return (
    <div className={classes.root}>
      <Head>
        <title>Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <TopBar />

      <main className={classes.main}>
        <Grid container spacing={1} m={1}>
          <Grid item xs={3} >
            <MenuBar selected={'Dashboard'} />
          </Grid>
          <Grid container item spacing={1} xs={4}>
            <Grid item xs={6} >
              <Container className={classes.countCard}>
                <Typography variant='h4' gutterBottom className={classes.countCardTitle}>
                  Total Gyms
                </Typography>
                <Box style={{
                  display: "flex",
                  flex: 1,
                  flexDirection: "column",
                  justifyContent: "center",
                  alignItems: "center",
                }}>
                  <Typography variant='h4' gutterBottom className={classes.countNumber} style={{
                    fontSize: clubsCount > 99999 ? '1.75rem' : '3rem',
                  }}>
                    {clubsCount}
                  </Typography>
                </Box>
              </Container>
            </Grid>
            <Grid item xs={6} >
              <Container className={classes.countCard}>
                <Typography variant='h4' gutterBottom className={classes.countCardTitle}>
                  Total Classes
                </Typography>
                <Box style={{
                  display: "flex",
                  flex: 1,
                  flexDirection: "column",
                  justifyContent: "center",
                  alignItems: "center",
                }}>
                  <Typography variant='h4' gutterBottom className={classes.countNumber} style={{
                    fontSize: classesCount > 99999 ? '1.75rem' : '3rem',
                  }}>
                    {classesCount}
                  </Typography>
                </Box>
              </Container>
            </Grid>
            <Grid item xs={6} >
              <Container className={classes.countCard}>
                <Typography variant='h4' gutterBottom className={classes.countCardTitle}>
                  Total Gyms
                </Typography>
                <Box style={{
                  display: "flex",
                  flex: 1,
                  flexDirection: "column",
                  justifyContent: "center",
                  alignItems: "center",
                }}>
                  <Typography variant='h4' gutterBottom className={classes.countNumber} style={{
                    fontSize: clubsCount > 99999 ? '1.75rem' : '3rem',
                  }}>
                    {clubsCount}
                  </Typography>
                </Box>
              </Container>
            </Grid>
            <Grid item xs={6} >
              <Container className={classes.countCard}>
                <Typography variant='h4' gutterBottom className={classes.countCardTitle}>
                  Total Classes
                </Typography>
                <Box style={{
                  display: "flex",
                  flex: 1,
                  flexDirection: "column",
                  justifyContent: "center",
                  alignItems: "center",
                }}>
                  <Typography variant='h4' gutterBottom className={classes.countNumber} style={{
                    fontSize: classesCount > 99999 ? '1.75rem' : '3rem',
                  }}>
                    {classesCount}
                  </Typography>
                </Box>
              </Container>
            </Grid>
          </Grid>
          <Grid item xs={5}>
            <MenuBar selected={'Dashboard'} />
          </Grid>
        </Grid>
      </main>
    </div >
  );
}
