import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head';
import MaterialTable from 'material-table';
import { Grid } from '@mui/material';
import { useStyles } from '../../../styles/classes/Index.style';
import { TopBar } from '../../../src/components/navigation/TopBar';
import { MenuBar } from '../../../src/components/navigation/MenuBar';
import { tableIcons } from '../../../src/components/table/MaterialTable';

export default function VideoAdmin() {
  const styles = useStyles();
  const router = useRouter();
  return (
    <div className={styles.root}>
      <Head>
        <title>Calfit Video</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <TopBar/>

      <main className={styles.main}>
        <Grid container spacing={2} m={2}>
          <Grid item xs={3}>
            <MenuBar selected={'Classes'} />
          </Grid>
          <Grid item xs={9}>
          </Grid>
        </Grid>
      </main>
    </div>
  );
}
